name: "Android ROM Build Tester"
author: 'ragebreaker'
description: "A GitHub action to test Android ROM buildability in the first hour"

inputs:
  REPO_INIT_CMD:
    description: 'Repo init command (e.g., LineageOS, AOSP manifest readme command)'
    required: true
    type: string
  MANIFEST_BRANCH:
    description: 'ROM Branch (e.g., lineage-20.0, android-13.0.0_r41)'
    required: true
    type: string
  LOCAL_MANIFEST:
    description: 'Raw local manifest link or repository'
    required: true
    type: string
  LOCAL_MANIFEST_BRANCH:
    description: 'Local Manifest Branch'
    default: ''
    type: string
  LUNCH_COMMAND:
    description: 'breakfast or lunch command'
    required: true
    type: string
    default: 'lunch lineage_blossom-userdebug'
  BUILD_COMMAND:
    description: 'Build Target (what to build)'
    default: 'mka bacon'
    type: string
  TEST_BUILD_DURATION:
    description: 'Maximum build test duration in minutes'
    default: '60'
    type: string

runs:
  using: 'composite'
  steps:
    - name: Setup Build Environment
      shell: bash
      run: |
        sudo apt-get update
        set +e
        sudo apt-get install -y bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick \
            lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev \
            libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev \
            python3 python2 openjdk-11-jdk
        set -e

    - name: Configure the 'repo' environment
      shell: bash
      run: |
        # Check if repo is already installed
        if ! command -v repo >/dev/null 2>&1; then
          echo "Repo not found. Installing now..."
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf "/home/$(whoami)/bin/repo" "/usr/bin/repo"
          echo "Repo installation complete."
        else
          echo "Repo already installed."
        fi

    - name: Sync Local Manifests and Repo
      shell: bash
      run: |
        rm -rf android
        mkdir android
        cd android
        
        # Initialize repo
        ${{ inputs.REPO_INIT_CMD }}
        
        # Setup local manifest
        mkdir -p .repo/local_manifests
        
        if [[ "${{ inputs.LOCAL_MANIFEST }}" =~ \.xml$ ]]; then
          curl -L "${{ inputs.LOCAL_MANIFEST }}" > .repo/local_manifests/local_manifest.xml
        else
          if [ -n "${{ inputs.LOCAL_MANIFEST_BRANCH }}" ]; then
            git clone "${{ inputs.LOCAL_MANIFEST }}" -b "${{ inputs.LOCAL_MANIFEST_BRANCH }}" .repo/local_manifests
          else
            git clone "${{ inputs.LOCAL_MANIFEST }}" .repo/local_manifests
          fi
        fi
        
        # Sync repositories
        timeout 30m repo sync -c --force-sync --no-clone-bundle --no-tags -j$(nproc --all) || \
          { exit_code=$?; [ $exit_code -eq 124 ] && echo "Timeout during sync" || (echo "Error: Process failed with exit code $exit_code"; exit $exit_code); }
        
        du -csh . # Output Size when done

    - name: Test Build
      shell: bash
      run: |
        cd android
        source build/envsetup.sh
        ${{ inputs.LUNCH_COMMAND }}
        export ALLOW_MISSING_DEPENDENCIES=true
        echo "Note: Allow missing dependencies is always true (to build only boot images for example) !"
        timeout ${{ inputs.TEST_BUILD_DURATION }}m ${{ inputs.BUILD_COMMAND }} -j$(nproc --all) || exit 1

    - name: Build Status Check
      shell: bash
      run: |
        if [ $? -eq 0 ]; then
          echo "BUILD_STATUS=success" >> $GITHUB_ENV
          echo "Build test completed successfully within time limit"
        else
          echo "BUILD_STATUS=failure" >> $GITHUB_ENV
          echo "Build test failed or exceeded time limit"
        fi

branding:
  icon: 'check-circle'
  color: 'green'
