name: Test ROM Build

on:
  push: 
    branches: '**'
  pull_request:
    branches: '**'
  
  workflow_dispatch:
    inputs:
      REPO_INIT_CMD:
        description: 'Repo init command (e.g., repo init -u https://github.com/LineageOS/android.git -b lineage-20.0)'
        required: true
        default: 'repo init -u https://github.com/LineageOS/android.git -b lineage-22.1 --git-lfs'
      LOCAL_MANIFEST:
        description: 'Raw local manifest link or repository URL'
        required: true
        default: 'https://raw.githubusercontent.com/mlm-games/android_local_manifests/refs/heads/rising-crdroid-lineage-22/m31s_a15.xml'
      LOCAL_MANIFEST_BRANCH:
        description: 'Local Manifest Branch (optional)'
        required: false
        default: ''
      LUNCH_COMMAND:
        description: 'Lunch command (e.g., lunch lineage_blossom-userdebug)'
        required: true
        default: 'lunch lineage_m31s-userdebug'
      BUILD_COMMAND:
        description: 'Build target (e.g., mka bacon)'
        required: false
        default: 'mka bacon'
      TEST_BUILD_DURATION:
        description: 'Maximum build test duration in minutes'
        required: false
        default: '60'

jobs:
  test-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main
      
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up environment variables
        run: |
          echo "Setting environment variables"
          export DEBIAN_FRONTEND=noninteractive
          export LANG=C
          export LANGUAGE=en_US:en
          export LC_ALL=C
          export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4G"
          export USER=$(whoami)
          
      - name: Install deps (some might be missing in the original action)
        run: |
          echo "Installing dependencies..."
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt update && sudo apt install -y locales && sudo locale-gen en_US.UTF-8
          set +e
          sudo apt install -y \
            git-core \
            gnupg \
            flex \
            bison \
            gperf \
            build-essential \
            zip \
            curl \
            zlib1g-dev \
            gcc-multilib \
            g++-multilib \
            libc6-dev-i386 \
            libncurses5 \
            lib32ncurses5-dev \
            x11proto-core-dev \
            libx11-dev \
            lib32z1-dev \
            ccache \
            libgl1-mesa-dev \
            libxml2-utils \
            xsltproc \
            unzip \
            python \
            wget \
            openjdk-8-jdk \
            android-tools-adb \
            android-tools-fastboot \
            schedtool \
            libssl-dev \
            bc \
            rsync \
            nano \
            vim \
            screen \
            imagemagick \
            lsof \
            python3 \
            python3-pip \
            locales \
            python2.7 \
            python-is-python2
          set -e

      - name: Initialize and Test ROM Build
        uses: mlm-games/initial-rom-build-tester@main
        with:
          REPO_INIT_CMD: ${{ github.event_name == 'workflow_dispatch' && inputs.REPO_INIT_CMD || 'repo init -u https://github.com/LineageOS/android.git -b cm-14.1' }}
          LOCAL_MANIFEST: ${{ github.event_name == 'workflow_dispatch' && inputs.LOCAL_MANIFEST || 'https://raw.githubusercontent.com/mlm-games/android_local_manifests/refs/heads/rising-crdroid-lineage-22/m31s_a15.xml' }}
          LOCAL_MANIFEST_BRANCH: ${{ github.event_name == 'workflow_dispatch' && inputs.LOCAL_MANIFEST_BRANCH || 'https://raw.githubusercontent.com/mlm-games/android_local_manifests/refs/heads/main/nicklaus_cm14_1.xml' }}
          LUNCH_COMMAND: ${{ github.event_name == 'workflow_dispatch' && inputs.LUNCH_COMMAND || 'breakfast nicklaus' }}
          BUILD_COMMAND: ${{ github.event_name == 'workflow_dispatch' && inputs.BUILD_COMMAND || 'make bacon' }}
          TEST_BUILD_DURATION: ${{ github.event_name == 'workflow_dispatch' && inputs.TEST_BUILD_DURATION || '60' }}

      - name: Initialize and Test ROM Build
        uses: mlm-games/initial-rom-build-tester@main
        with:
          REPO_INIT_CMD: ${{ inputs.REPO_INIT_CMD }}
          LOCAL_MANIFEST: ${{ inputs.LOCAL_MANIFEST }}
          LOCAL_MANIFEST_BRANCH: ${{ inputs.LOCAL_MANIFEST_BRANCH }}
          LUNCH_COMMAND: ${{ inputs.LUNCH_COMMAND }}
          BUILD_COMMAND: ${{ inputs.BUILD_COMMAND }}
          TEST_BUILD_DURATION: ${{ inputs.TEST_BUILD_DURATION }}
